name: 'jira_source'
version: '0.1.0'
config-version: 2
require-dbt-version: [">=0.18.0", "<0.19.0"]


vars:
  jira_schema: jira_3

  jira_source:
    issue: "{{ source('jira', 'issue') }}"
    project: "{{ source('jira', 'project') }}"
    board: "{{ source('jira', 'board') }}"
    user: "{{ source('jira', 'user') }}"
    epic: "{{ source('jira', 'epic') }}"
    issue_type: "{{ source('jira', 'issue_type') }}"
    status: "{{ source('jira', 'status') }}"
    resolution: "{{ source('jira', 'resolution') }}"
    priority: "{{ source('jira', 'priority') }}"
    issue_multiselect_history: "{{ source('jira', 'issue_multiselect_history') }}"
    issue_field_history: "{{ source('jira', 'issue_field_history') }}"
    comment: "{{ source('jira', 'comment') }}"
    issue_link: "{{ source('jira', 'issue_link') }}"
    component: "{{ source('jira', 'component') }}"
    field: "{{ source('jira', 'field') }}"
    sprint: "{{ source('jira', 'sprint') }}"


models: 
  materialized: table # for building the package, switch to views later? 

profile: dev_bigquery_dbt_testing