name: 'jira_source_integration_tests'
version: '1.0.0'
config-version: 2
profile: 'integration_tests'


vars:
  jira_source:
      board: "{{ ref('board') }}"
      comment: "{{ ref('comment') }}"
      component: "{{ ref('component') }}"
      epic: "{{ ref('epic') }}"
      field_option: "{{ ref('field_option') }}"
      issue_field_history: "{{ ref('issue_field_history') }}"
      field: "{{ ref('field') }}"
      field: "{{ ref('field') }}"
      field: "{{ ref('field') }}"
      field: "{{ ref('field') }}"
      field: "{{ ref('field') }}"
      field: "{{ ref('field') }}"

      using_bool: True
      using_bool_2: True

seeds:
  PACKAGE_NAME_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    table:
      +column_types:
        create_time: timestamp
        start_time: timestamp
    table_2:
      +column_types:
        create_time: timestamp
        start_time: timestamp
        send_time: timestamp

